/**
 * Copies the design system into the app: tokens.css and tz.css, the two fonts, the logos and the icons.
 * The design system (../design-system) is the source of truth; nothing here is edited by hand.
 *
 *   npm run sync:ds          write the copies
 *   npm run sync:ds -- --check   fail when a copy differs from the design system (used by npm run build)
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ds = path.resolve(app, '../design-system');
const check = process.argv.includes('--check');

const FILLED = new Set(['facebook', 'instagram', 'google', 'whatsapp']);

type Target = { dest: string; content: Buffer };

function iconModule(): string {
	const dir = path.join(ds, 'assets/icons');
	const names = readdirSync(dir)
		.filter((f) => f.endsWith('.svg'))
		.map((f) => f.slice(0, -4))
		.sort();
	const entries = names.map((name) => {
		let svg = readFileSync(path.join(dir, `${name}.svg`), 'utf8');
		svg = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/<metadata>[\s\S]*?<\/metadata>/g, '');
		svg = svg.replace(/<title>[\s\S]*?<\/title>/g, '');
		const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? '0 0 24 24';
		const inner = svg
			.replace(/^[\s\S]*?<svg[^>]*>/, '')
			.replace(/<\/svg>[\s\S]*$/, '')
			.replace(/\s+/g, ' ')
			.replace(/>\s+</g, '><')
			.trim();
		return `\t${JSON.stringify(name)}: { viewBox: ${JSON.stringify(viewBox)}, filled: ${FILLED.has(name)}, body: ${JSON.stringify(inner)} }`;
	});
	return (
		'// GENERATED by scripts/sync-design-system.ts from design-system/assets/icons. Do not edit by hand.\n' +
		'// Lucide (ISC), Simple Icons (CC0) and the TuinZorg DP custom icons mower and grass.\n' +
		'export const icons = {\n' +
		entries.join(',\n') +
		'\n} as const;\n\nexport type IconName = keyof typeof icons;\n'
	);
}

function targets(): Target[] {
	const list: Target[] = [];
	const copy = (from: string, to: string) =>
		list.push({ dest: path.join(app, to), content: readFileSync(path.join(ds, from)) });

	copy('css/tokens.css', 'src/lib/styles/tokens.css');
	copy('css/tz.css', 'src/lib/styles/tz.css');
	copy(
		'fonts/BricolageGrotesque-Variable.woff2',
		'src/lib/fonts/BricolageGrotesque-Variable.woff2'
	);
	copy('fonts/Figtree-Variable.woff2', 'src/lib/fonts/Figtree-Variable.woff2');
	for (const logo of [
		'tz-logo.svg',
		'tz-logo-on-dark.svg',
		'tz-mark.svg',
		'tz-logo-mono-forest.svg',
		'tz-logo-mono-white.svg'
	]) {
		copy(`assets/logo/${logo}`, `static/logo/${logo}`);
	}
	copy('assets/logo/tz-mark.svg', 'static/favicon.svg');
	list.push({ dest: path.join(app, 'src/lib/icons/icons.ts'), content: Buffer.from(iconModule()) });
	return list;
}

// Git may check text files out with CRLF on Windows; compare them line-ending agnostic.
const CR = String.fromCharCode(13);
const normalise = (file: string, b: Buffer) =>
	/[.](css|svg|ts)$/.test(file) ? Buffer.from(b.toString('utf8').split(CR).join('')) : b;

const drift: string[] = [];
for (const t of targets()) {
	const same =
		existsSync(t.dest) &&
		normalise(t.dest, readFileSync(t.dest)).equals(normalise(t.dest, t.content));
	if (same) continue;
	if (check) {
		drift.push(path.relative(app, t.dest));
	} else {
		mkdirSync(path.dirname(t.dest), { recursive: true });
		writeFileSync(t.dest, t.content);
		console.log(`synced ${path.relative(app, t.dest)}`);
	}
}

if (check && drift.length) {
	console.error(
		`These files differ from design-system/. Change the design system, then run npm run sync:ds:\n  ${drift.join('\n  ')}`
	);
	process.exit(1);
}
if (check) console.log('design system copies are in sync');
