/**
 * After vite build: wraps the adapter's worker so the same Worker also answers the cron triggers.
 * The adapter's entry has no `scheduled` handler; this one forwards each cron to an internal route
 * (/api/cron/daily, /api/cron/google) guarded by CRON_SECRET.
 */
import { appendFileSync, existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { APP_DIR } from './lib/env';

const dir = path.join(APP_DIR, '.svelte-kit/cloudflare');
const entry = path.join(dir, '_worker.js');
const inner = path.join(dir, '_sveltekit_worker.js');

if (!existsSync(entry)) {
	console.error('[wrap-worker] .svelte-kit/cloudflare/_worker.js not found; run vite build first.');
	process.exit(1);
}
if (readFileSync(entry, 'utf8').includes('tz-cron-wrapper')) {
	console.log('[wrap-worker] already wrapped');
	process.exit(0);
}

renameSync(entry, inner);
writeFileSync(
	entry,
	`// tz-cron-wrapper: generated by scripts/wrap-worker.ts
import app from './_sveltekit_worker.js';

const ROUTES = { '0 3 * * *': '/api/cron/daily', '30 4 * * *': '/api/cron/google' };

export default {
	fetch: (request, env, ctx) => app.fetch(request, env, ctx),
	async scheduled(controller, env, ctx) {
		const route = ROUTES[controller.cron];
		if (!route || !env.CRON_SECRET) return;
		const origin = (env.PUBLIC_SITE_URL || 'https://tuinzorgdp.be').replace(/\\/$/, '');
		const request = new Request(origin + route, { method: 'POST', headers: { 'x-cron-secret': env.CRON_SECRET } });
		ctx.waitUntil(app.fetch(request, env, ctx).then((r) => console.log('cron', controller.cron, r.status)));
	}
};
`
);
// Server code must never be served as a static asset.
appendFileSync(path.join(dir, '.assetsignore'), '\n_sveltekit_worker.js\n');
console.log('[wrap-worker] added the scheduled handler');
